//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JOEntities : DbContext
    {
        public JOEntities()
            : base("name=JOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_apc_personnel> tbl_apc_personnel { get; set; }
        public virtual DbSet<tbl_applications> tbl_applications { get; set; }
        public virtual DbSet<tbl_cc_category> tbl_cc_category { get; set; }
        public virtual DbSet<tbl_costcenter_meaning> tbl_costcenter_meaning { get; set; }
        public virtual DbSet<tbl_daily_report> tbl_daily_report { get; set; }
        public virtual DbSet<tbl_downtime> tbl_downtime { get; set; }
        public virtual DbSet<tbl_downtime_cause> tbl_downtime_cause { get; set; }
        public virtual DbSet<tbl_employee_outside_rimp> tbl_employee_outside_rimp { get; set; }
        public virtual DbSet<tbl_employees> tbl_employees { get; set; }
        public virtual DbSet<tbl_gantt_chart> tbl_gantt_chart { get; set; }
        public virtual DbSet<tbl_jo_cc_details> tbl_jo_cc_details { get; set; }
        public virtual DbSet<tbl_joborder> tbl_joborder { get; set; }
        public virtual DbSet<tbl_joborder_category> tbl_joborder_category { get; set; }
        public virtual DbSet<tbl_joborder_details> tbl_joborder_details { get; set; }
        public virtual DbSet<tbl_managers_email> tbl_managers_email { get; set; }
        public virtual DbSet<tbl_network> tbl_network { get; set; }
        public virtual DbSet<tbl_preventive_maintenance> tbl_preventive_maintenance { get; set; }
        public virtual DbSet<tbl_preventive_pc> tbl_preventive_pc { get; set; }
        public virtual DbSet<tbl_preventive_services> tbl_preventive_services { get; set; }
        public virtual DbSet<tbl_priority> tbl_priority { get; set; }
        public virtual DbSet<tbl_sbu> tbl_sbu { get; set; }
        public virtual DbSet<tbl_sbu_costcenter> tbl_sbu_costcenter { get; set; }
        public virtual DbSet<tbl_scoping> tbl_scoping { get; set; }
        public virtual DbSet<tbl_security> tbl_security { get; set; }
        public virtual DbSet<tbl_server> tbl_server { get; set; }
        public virtual DbSet<tbl_status> tbl_status { get; set; }
        public virtual DbSet<tbl_sub_assignees> tbl_sub_assignees { get; set; }
        public virtual DbSet<tbl_telephone> tbl_telephone { get; set; }
        public virtual DbSet<tbl_telephone_Rolie> tbl_telephone_Rolie { get; set; }
    }
}
