//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_preventive_maintenance
    {
        public int maintenance_id { get; set; }
        public Nullable<int> pc_id { get; set; }
        public string planned_month { get; set; }
        public string preventive_year { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> actual_date { get; set; }
        public string incharge { get; set; }
        public string prepared_by { get; set; }
        public string checked_by { get; set; }
        public string approved_by { get; set; }
    }
}
