//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_joborder_details
    {
        public int details_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public string sw_codenumber { get; set; }
        public Nullable<int> sw_standard_time { get; set; }
        public Nullable<System.DateTime> date_target { get; set; }
        public Nullable<System.DateTime> date_assigned { get; set; }
        public Nullable<System.DateTime> date_started { get; set; }
        public Nullable<System.DateTime> date_ended { get; set; }
        public Nullable<int> actual_time { get; set; }
        public string details { get; set; }
        public string purpose { get; set; }
        public string diagnosis { get; set; }
        public string action_taken { get; set; }
        public string reason_delay { get; set; }
        public string apc_noted_by { get; set; }
        public string apc_approved_by { get; set; }
        public Nullable<int> progress_rate { get; set; }
        public Nullable<System.DateTime> date_progress_updated { get; set; }
        public string assignee { get; set; }
        public string remarks { get; set; }
        public string has_scope { get; set; }
        public string sw_gantt_chart { get; set; }
        public string flg_is_exported { get; set; }
    }
}
