//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_downtime
    {
        public int downtime_id { get; set; }
        public Nullable<int> downtime_type_id { get; set; }
        public string code_number { get; set; }
        public Nullable<System.DateTime> datestarted_of_downtime { get; set; }
        public Nullable<System.DateTime> dateended_of_downtime { get; set; }
        public Nullable<int> total_mins_of_downtime { get; set; }
        public string downtime_cause_details { get; set; }
        public Nullable<int> downtime_cause_id { get; set; }
    }
}
