//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_joborder
    {
        public int jobno_id { get; set; }
        public Nullable<int> details_id { get; set; }
        public string job_no { get; set; }
        public Nullable<int> priority_id { get; set; }
        public Nullable<System.DateTime> date_filed { get; set; }
        public Nullable<System.DateTime> date_needed { get; set; }
        public string shift_hrs { get; set; }
        public Nullable<int> hrs_of_ot { get; set; }
        public string requested_by { get; set; }
        public string noted_by { get; set; }
        public string approved_by { get; set; }
        public string noted_by_sign { get; set; }
        public string approved_by_sign { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<System.DateTime> date_confirmed { get; set; }
    }
}
