//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jo_cc_details
    {
        public int jo_cc_id { get; set; }
        public Nullable<int> jobno_id { get; set; }
        public string category { get; set; }
        public string sbu { get; set; }
        public string division { get; set; }
        public string cost_center { get; set; }
        public string description { get; set; }
    }
}
