//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_preventive_pc
    {
        public int pc_id { get; set; }
        public string computer_name { get; set; }
        public string equipment { get; set; }
        public string owner { get; set; }
        public string department { get; set; }
    }
}
