//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_apc_personnel
    {
        public int apc_id { get; set; }
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string tel_num { get; set; }
        public string status { get; set; }
    }
}
