//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee_outside_rimp
    {
        public int or_id { get; set; }
        public string visitor_id { get; set; }
        public string visitor_name { get; set; }
        public string visitor_company_id { get; set; }
        public string visitor_company_name { get; set; }
        public string visitor_position { get; set; }
    }
}
