//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_applications
    {
        public int app_id { get; set; }
        public Nullable<int> apc_id { get; set; }
        public string code_number { get; set; }
        public string application_name { get; set; }
        public string user_department { get; set; }
        public string app_type { get; set; }
        public string web_link { get; set; }
        public string icon_path { get; set; }
        public string is_active { get; set; }
    }
}
