//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_scoping
    {
        public int id { get; set; }
        public Nullable<int> batch_no { get; set; }
        public string jo_no { get; set; }
        public string system_name { get; set; }
        public string background { get; set; }
        public string system_goals { get; set; }
        public string system_objectives { get; set; }
        public string deliverables { get; set; }
        public string development_estimation { get; set; }
        public string confirmedby_user { get; set; }
        public string preparedby { get; set; }
        public string confirmedby_superior { get; set; }
        public Nullable<System.DateTime> date_confrimedbyuser { get; set; }
        public Nullable<System.DateTime> date_confrimedbysuperior { get; set; }
        public Nullable<bool> is_saved { get; set; }
    }
}
