//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_daily_report
    {
        public int r_id { get; set; }
        public string apc_id { get; set; }
        public string jobno { get; set; }
        public System.DateTime date { get; set; }
        public string day { get; set; }
        public string time_start { get; set; }
        public string time_end { get; set; }
        public int mins { get; set; }
        public string cc_description { get; set; }
        public string work_description { get; set; }
        public string company { get; set; }
    }
}
